### ISSUE TITLE
Create links to ProfilePage component

### ISSUE THREAD

**Issue by Joelzor** [boolean-uk/team-dev-frontend-client#105]
### Create button/link in header / sidebar - to user's own profile

- Edit Header CSS to create a Link to the ProfilePage component, basic styling for now. 
- Take id from LoggedInUser state

### Link to ProfilePage in Posts 

- Talk with Posts team- when clicking on a username (writer of each post), link again to ProfilePage
- Get each correct ID and pass into Link

### Link through searchbar 

- When search bar displays results, link to the correct profile
- id for link probably coming from mapping through results

**Comment by dogezen** [comment]
@Joelzor - note this is a duplicate in some way of ISSUE https://github.com/boolean-uk/team-dev-frontend-client/issues/101

Please let me know if I can close 101 or whether you wish to bring in some details from 101.

As Lewis mentioned, please be more specific with how the `id` is to be taken from `loggedInUser`, ie:
- pass `loggedInUser` from App.js to the Header component and access the `.id` property.
- The ID property will be added to a `<Link>` component that points to the path `/profiles/:id`, so for user with ID=12, the link will point to `/profiles/12`

This is the level of detail needed, because it includes instructions on how to check/validate this.

Also note that the HEADER component has some nicely formatted buttons (including a logout button). You may use the same CSS styling for your Profile button.

Link through search bar: you won't be able to do any code at the moment about this because we have not yet scoped/planned what will happen with the search bar / how this will be used.

**Comment by Joelzor** [comment]
Ah, we didn't see the other issue. You can remove this issue instead actually!

**Comment by dogezen** [comment]
OK, will close this issue
