### ISSUE TITLE
Create Edit Button

### ISSUE THREAD

**Issue by Dex491** [boolean-uk/team-dev-frontend-client#107]
### Creating Edit Link
- In the profile view component the details are NOT editable, and there will be a button to take the user to the edit component
	- Just display the db values in p/li tags
	- There will be a ProfileEdit.js for that later

- The edit button should only be viewable/usable for the teacher or the user that matches the id
	- Use conditional rendering to check if the user id matches or if the user is a teacher
	- If the role of the user is TEACHER or if the loggedInUser id matches the profile id, then display the edit button - or have edit button greyed out or possibly add an error message if a user without perms tries to edit

- When user clicks on the Edit button (which is a Link), we navigate to `profile/:id/edit` - we take this id directly from the current profile being viewed

**Comment by dogezen** [comment]
OK, I think this is quite clear, just to be super specific, this edit button will appear in the `ProfilePage.js`? Whoever works on this, will they know where this file is? Will it already have been created? Where are they getting loggedInUser (from props right?)

I think you need to mark this issue as DEPENDENT on the issue where you create the basic profilepage.js so that whoever works on this only starts working on it after the page exists or the other issue has been completed / approved.

**Comment by dogezen** [comment]
On click of edit button, what will happen? Are you going to LINK to another page? If so, what URL?
