### ISSUE TITLE
Authentication for accessing ProfileEdit

### ISSUE THREAD

**Issue by Dex491** [boolean-uk/team-dev-frontend-client#108]
### Auth checks in ProfileEdit

- If a student visits another student's or a teachers edit page, they should be redirected to the normal profile page for that user.
    - If the role is student && the `loggedInUser.id`  ≠ `profileToEdit.id` - navigate back to the profile page of the id they wanted to edit
- If the loggedinUser has a role of student, we add disabled attribute to cohort select
- For a teacher role, we disable the password input if the `loggedInUser.id` doesn’t match the `profileToEdit.id`

**Comment by dogezen** [comment]
I would suggest passing the `loggedInUser` from app.js to your `ProfilePage`.

Inside that component then you can check: if loggedInUser is teacher, you render TeacherProfilePage, if not, you render StudentProfilePage (or just have 1 single profile page with conditional rendering)

You should put the ROUTE for the profile pages inside the `<Route element={<AuthenticateUser teacherOnly=true />}>` in app.js so that it guarantees the user is at least logged in or automatically redirects to login if not.
