### ISSUE TITLE
Fix cohort display in ProfilePage and EditProfile

### ISSUE THREAD

**Issue by Joelzor** [boolean-uk/team-dev-frontend-client#153]
## ProfilePage.js

- Fetch cohort data `/cohorts/:id` - use cohortId in user data to get the correct cohort - second useEffect
- use the fetched cohort data to display the cohort's name

## ProfileEdit.js

- Make a GET request to get all cohorts - `/cohorts` endpoint - in a useEffect - we fetch the data as soon as page loads
- Make cohort input a dropdown (select) - the user can choose from the list of current cohort options- we use the data fetched in the first step
- When the user clicks one of the cohorts, we assign that cohort id as the user's cohort- in handleChange

**Comment by dogezen** [comment]
I would suggest you actually send a request for the cohort data, by id.

So that you can then extract the cohort's name, once you fetch it from API.

Finally, the choice of cohort would be better done as a dropdown: you can fetch a list of all cohorts, and display a dropdown with all cohort names. On click of an option, then you assign that option's cohort id as the new cohort for the user.

**Comment by Joelzor** [comment]
> I would suggest you actually send a request for the cohort data, by id.

Could you clarify this? In the API endpoints, we only have an endpoint for getting all cohorts. I'm not sure how we could get a single cohorts data using a user id

**Comment by dogezen** [comment]
Actually, we forgot to document this endpoint, but you can get a cohort by id: `/cohorts/:id`
